let ChainTypes = {};

ChainTypes.reserved_spaces = {
  relative_protocol_ids: 0,
  protocol_ids: 1,
  implementation_ids: 2
};

ChainTypes.object_type = {
  null: 0,
  base: 1,
  account: 2,
  asset: 3,
  force_settlement: 4,
  committee_member: 5,
  witness: 6,
  limit_order: 7,
  call_order: 8,
  custom: 9,
  proposal: 10,
  operation_history: 11,
  withdraw_permission: 12,
  vesting_balance: 13,
  worker: 14,
  balance: 15,
  restricted_account: 16,
  allow_create_asset: 17,
  fund: 18
};

ChainTypes.impl_object_type = {
  global_property: 0,
  dynamic_global_property: 1,
  index_meta: 2,
  asset_dynamic_data: 3,
  asset_bitasset_data: 4,
  account_balance: 5,
  account_statistics: 6,
  transaction: 7,
  block_summary: 8,
  account_transaction_history: 9,
  blinded_balance: 10,
  chain_property: 11,
  witness_schedule: 12,
  budget_record: 13,
  deposit: 21
};

ChainTypes.vote_type = {
  committee: 0,
  witness: 1,
  worker: 2
};

ChainTypes.operations = {
  transfer: 0,
  limit_order_create: 1,
  limit_order_cancel: 2,
  call_order_update: 3,
  fill_order: 4,
  account_create: 5,
  account_update: 6,
  account_whitelist: 7,
  account_upgrade: 8,
  account_transfer: 9,
  asset_create: 10,
  asset_update: 11,
  asset_update_bitasset: 12,
  asset_update_feed_producers: 13,
  asset_issue: 14,
  asset_reserve: 15,
  asset_fund_fee_pool: 16,
  asset_settle: 17,
  asset_global_settle: 18,
  asset_publish_feed: 19,
  witness_create: 20,
  witness_update: 21,
  proposal_create: 22,
  proposal_update: 23,
  proposal_delete: 24,
  withdraw_permission_create: 25,
  withdraw_permission_update: 26,
  withdraw_permission_claim: 27,
  withdraw_permission_delete: 28,
  committee_member_create: 29,
  committee_member_update: 30,
  committee_member_update_global_parameters: 31,
  vesting_balance_create: 32,
  vesting_balance_withdraw: 33,
  worker_create: 34,
  custom: 35,
  assert: 36,
  balance_claim: 37,
  override_transfer: 38,
  transfer_to_blind: 39,
  blind_transfer: 40,
  transfer_from_blind: 41,
  asset_settle_cancel: 42,
  asset_claim_fees: 43,
  asset_claim_fees_operation: 44,
  bonus_operation: 45,
  asset_daily_bonus: 46,
  asset_referrals_bonus: 47,
  edc_asset_fund_fee_pool: 48,
  account_restrict_operation: 49,
  account_allow_referrals_operation: 50,
  set_online_time_operation: 51,
  set_verification_is_required_operation: 52,
  allow_create_asset: 53,
  add_address: 54,
  asset_update2: 55,
  fund_create: 56,
  fund_update: 57,
  fund_refill: 58,
  fund_deposit: 59,
  fund_withdrawal: 60,
  fund_payment: 61,
  fund_set_enable: 62,
  fund_deposit_set_enable: 63,
  fund_remove: 64,
  allow_create_addresses: 65,
  set_burning_mode: 66,
  assets_update_fee_payer: 67,
  asset_update_exchange_rate: 68,
  fund_change_payment_scheme: 69,
  enable_autorenewal_deposits: 70,
  update_blind_transfer2_settings: 71,
  blind_transfer2: 72,
  deposit_renewal: 73,
  set_market: 74,
  cheque_create: 75,
  cheque_use: 76,
  cheque_reverse: 77,
  create_market_address: 78,
  account_update_authorities: 79,
  update_settings: 80,
  account_edc_limit_daily_volume: 81,
  fund_deposit_update: 82,
  fund_deposit_reduce: 83,
  fund_deposit_update2: 84,
  update_accounts_referrer: 88,
  enable_account_referral_payments: 89,
};

module.exports = ChainTypes;
